[package]
name = "quote-scraper"
version = "0.1.0"
authors = ["hr567 <hr567@hr567.me>"]
edition = "2021"

[dependencies]
reqwest = "0.12.22"
scraper = "0.23.1"
tokio = { version = "1.47.1", features = ["macros", "sync"] }
url = "2.5.4"
